server:
  maxHttpHeaderSize: "8999"
  servlet:
    encoding:
      force-response: true
  port: 80
spring:
  #datasource--mysql的数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.137.85:3306/photoapp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: A1223176327a
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    hikari:
      max-lifetime: 500000
  jackson:
    #返回的JSON数据中如果属性未NULL时，不序列化该键值对。(全服务设置，谨慎使用)
    default-property-inclusion: non_null
  mvc:
    servlet:
      #设置为0或正数，启动时初始化
      load-on-startup: 100
#配置mybatis
mybatis:
  #给mapper.xml 中需要使用的实体类起别名，直接扫描包的形式进行操作。
  type-aliases-package: cn.xinill.smart_photo.pojo
  #配置mapper.xml的映射  支持通配符
  mapper-locations: classpath:mapper/*Mapper.xml
